/**   Demonstrates the behavior of a nested finally block.*/public class GetMilk2{   public static void main(String[] args)   {      try      {         try         {            openRefrigerator();            takeOutMilk();            pourMilk();            putBackMilk();         }         finally         {            closeRefrigerator();         }      }      catch (NoMilkException e)      {         System.out.println(e.getMessage());      }   } // end main      public static void openRefrigerator()   {      System.out.println("Open the refrigerator door.");   } // end openRefrigerator      public static void takeOutMilk() throws NoMilkException   {      if (Math.random() < 0.5)         System.out.println("Take out the milk.");      else         throw new NoMilkException("Out of Milk!");   } // end openRefrigerator      // < The methods pourMilk, putBackMilk, and closeRefrigerator are analogous to   //   openRefrigerator and are here. >   // . . .} // end GetMilk2